### ISSUE TITLE
Stable release?

### ISSUE THREAD

**Issue by sagikazarmark** [php-http/guzzle5-adapter#19]
Should we release this as well? There is an indirect dependency on discovery which is not yet stable.

**Comment by Nyholm** [comment]
I see no reason to rush it. I believe you ask the question because you are not convinced and I am not convinced myself. Let's wait out any possible changes in discovery or Puli. 

Or am I too defensive?

**Comment by sagikazarmark** [comment]
My concerns exactly.

**Comment by sagikazarmark** [comment]
Nevertheless, I released 0.4

**Comment by Nyholm** [comment]
:+1:

**Comment by Nyholm** [comment]
We had the discussion in other repositories and I want to write it down here. 
I suggest not to tag 1.0 for `php-http/guzzle5-adpater` until we have removed or tagged the `php-http/discovery` to 1.0.

**Comment by sagikazarmark** [comment]
I think we can finally tag this as well

**Comment by sagikazarmark** [comment]
Done in https://github.com/php-http/guzzle5-adapter/tree/v1.0.0
