### ISSUE TITLE
Guzzle 6 adapter

### ISSUE THREAD

**Issue by ddeboer** [php-http/guzzle5-adapter#2]
Could you create a guzzle6-adapter repo? I’d be willing to work on the code.

**Comment by sagikazarmark** [comment]
I've created a repository  with some basic content, but please keep the following in mind:
- The interfaces are not finished (yet). Guzzle 5 is the example implementation
- Currently I am working on some separation logic, see the internal_separation branches in the relevant repositories

I've also added the package to packagist, travis and scrutinizer
