### ISSUE TITLE
Support of the 7.1 php version?

### ISSUE THREAD

**Issue by o1eksiy** [php-http/guzzle5-adapter#32]

**Comment by Nyholm** [comment]
Of course. Can you add it to travis.yml?

**Comment by o1eksiy** [comment]
@Nyholm, I tried to make a commit, but I got this error: "Permission to php-http/guzzle5-adapter.git denied to o1eksiy."

**Comment by Nyholm** [comment]
You need to fork the project first, then make the commit and push it to your fork. After that you have to make a Pull Request which allows me to review the changes. When I'm happy (or any other maintainer are happy) I will merge your commit to this repository. 

See github docs: https://help.github.com/articles/github-flow/

**Comment by dbu** [comment]
we test with php 7.0, 7.1, 7.2 and 7.3 now
