### ISSUE TITLE
Mark package as abanonded

### ISSUE THREAD

**Issue by GrahamCampbell** [php-http/guzzle5-adapter#37]
Guzzle 5 is officially dead now. Should we abandon this package and point to the guzzle 6 bridge as the replacement?

(Abandon = mark as abandoned on both github (in the repo settings) and packagist.)

**Comment by dbu** [comment]
:+1: 

do you agree @sagikazarmark and @Nyholm ?

**Comment by Nyholm** [comment]
No. There is no benefit and there is no massive maintainance burden here.

**Comment by GrahamCampbell** [comment]
Ping.

**Comment by Uebix** [comment]
Guzzle 5 is officially dead now, is true, but many CMS use Guzzle 5 because is difficult to upgrade without break backward compatibility. So this package is useful.

**Comment by GrahamCampbell** [comment]
The package is still abandoned, either way. Composer just doesn't warn people.

**Comment by dbu** [comment]
doing it now as part of https://github.com/php-http/documentation/pull/310/
